# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 52771fa0cebef4a475d88cb26c69769c1997b736af9717ab0c438d6eae0c190a5130ecefe941c10b1f489900b40ef900bd87c50570c0fe7a6efa636d090fb72c

test:
  secret_key_base: e9916e8f6be5551b278baff55e12cee4e4c3c1bd410122440060cc95430151db32dd763b289e42bc8522725da8a6483802eb0aa6b5db3e6069a5584447042478

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
